# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Test PROD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: "Build & Test"
    runs-on: windows-latest
    environment: PROD
    env:
      PAGEID: ${{ vars.PAGEID }}
      METAACCESSTOKEN: ${{ secrets.METAACCESSTOKEN }}
    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    # - name: Verify solution Path
    #   run: dir /a $SLN_FILE
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
    - name: List TestResults
      run: dir TestResults
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure() # run this step even if previous step failed
      with:
        name: Test Report # Name of the job run which will be created
        reporter: dotnet-trx # Format of test results
        list-tests: "all"
        fail-on-error: "false"
        path: TestResults/test-results.trx #uses linux path even if windows is used in runs-on
